### ISSUE TITLE
ModalBubble not showing in Droid within MasterDetail Page

### ISSUE THREAD

**Issue by toniObject** [baskren/Forms9PatchDemo#2]
When calling the bubble within a Detail Page of MasterDetail Class don't show the bubble in Android. It works well in iOS. Here is example code written in a OnAppearing function of a detail page:

`protected override void OnAppearing()
		{
			base.OnAppearing();

			var modal = new Forms9Patch.ModalPopup
			{
				Content = new Forms9Patch.StackLayout
				{
					Children = {
								new Xamarin.Forms.Label {
									Text = "Hello Modal popup!",
									TextColor = Color.Black}
							},
					BackgroundColor = Color.FromRgb(100, 100, 100),
					Padding = 20,
				},
				OutlineRadius = 4,
				OutlineWidth = 1,
				OutlineColor = Color.Black,
				BackgroundColor = Color.Aqua,
				HasShadow = true,
				HeightRequest = 200,
				WidthRequest = 200,
			};
			modal.BindingContext = this;
			modal.IsVisible = true;
}`

**Comment by baskren** [comment]
@toniObject -- I am just now seeing this issue.  Are you still having this problem?

**Comment by baskren** [comment]
No response from the original poster.  Marking closed.
