### ISSUE TITLE
Reference errors in the project

### ISSUE THREAD

**Issue by Shan11812** [baskren/Forms9PatchDemo#3]
Projects use references that are not inside the packages folder
ex: https://github.com/baskren/Forms9PatchDemo/blob/master/Forms9PatchDemo/Forms9PatchDemo.csproj#L131
```
<Reference Include="Xamarin.Forms.Core">
<HintPath>..\..\..\..\.nuget\packages\Xamarin.Forms.2.3.4.231\lib\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10+xamarinmac20\Xamarin.Forms.Core.dll</HintPath>
</Reference>
```
I'm using XamarinStudio 6.1.1
After NuGet restore while trying to build the project these references are still missing.

**Comment by baskren** [comment]
Yes, this is an example where my work around for Xamarin.Studio / Visual.Studio's weak support for git submodules can bite me.  In my environment, I've setup Nuget.config to put packages in ```~/.nuget/packages```  by adding the following:

```
<config>
    <add key="repositoryPath" value="/Users/ben/.nuget/packages"/>
</config>
```

Then, I have an environment variable called ```$(NUGET_PACKAGES)``` that points to ```~/.nuget/packages```.  Before I git commit a ```.csproj``` file, I swap the relative paths of the nuget packages to ```$(NUGET_PACKAGES)```.   As a result, when I bring in one of my git submodules configured this way, all the package dependencies point to the same place (and I don't get the exact error you just did!).  I do a lot of submodules so this solution works great ... for me.    

Unfortunately, I don't have an automated way to NOT doing this for some solutions/projects.  So, the last time I updated packages in this solution, I forgot to turn off the above change to Nuget.config.

LT;DR; I've just pushed a update to this demo project that corrects the relative paths.  Please let me know if it does or doesn't fix this issue for you.

**Comment by Shan11812** [comment]
Yes, its working now. Thanks.
