### ISSUE TITLE
BubblePopup often not pointing to target

### ISSUE THREAD

**Issue by Kizari** [baskren/Forms9PatchDemo#6]
The BubblePopup control is very inconsistent with pointing at the target element. The expected behaviour is that the Bubble will always have a pointer pointing at the target VisualElement. The outcome is that many of the times the BubblePopup is used, it displays in the center of the screen without a pointer.

The code I am using to create and display the bubble is as follows.

```
            Forms9Patch.Button closeButton = new Forms9Patch.Button
            {
                Text = "Close",
                OutlineColor = Color.Transparent,
                BackgroundColor = Color.Transparent,
                FontSize = 14,
                Padding = new Thickness(0, 0, 0, 0),
                HorizontalOptions = LayoutOptions.FillAndExpand,
                HorizontalTextAlignment = TextAlignment.Start
            };

            BubblePopup popup = new BubblePopup(MyVisualElement)
            {
                BackgroundColor = Color.White,
                OutlineRadius = 10,
                PointerDirection = PointerDirection.Vertical,
                PointerLength = 15,
                PointerTipRadius = 0,
                PointerCornerRadius = 0,
                PageOverlayColor = Color.Transparent,
                TargetBias = 0.5,
                HasShadow = false,
                CancelOnBackButtonClick = false,
                CancelOnPageOverlayTouch = true,
                Content = new Xamarin.Forms.StackLayout
                {
                    Padding = 7,
                    Children =
                    {
                        new Forms9Patch.Label
                        {
                            Text = message,
                            TextColor = Color.Black
                        },
                        closeButton
                    }
                }
            };

            popup.IsVisible = true;
```

In the above example, "MyVisualElement" is a reference to a VisualElement in the XAML, for example:

`<Label x:Name="MyVisualElement" Text="Test Label" />`

I have also tried using different pointer directions, but it doesn't help.

I am running the latest version of Xamarin Forms (3.4.0.1008975 at time of writing) and the latest version of Forms9Patch (1.6.4 at time of writing). The issue is inconsistent across devices as well, for example, more of the bubbles (but not all) are successful on my Galaxy Note8 than on my iPhone 5s. Whether this is due to the device size or the platform I don't know.

**Comment by baskren** [comment]
@Kizari -

This is likely the intended behavior.  If the element is off of the screen **OR** within the BubblePopup.Margin, then the pointer of the bubble popup cannot touch the Target.  So, to address this, BubblePopup gracefully fails by displaying the content in a ModalPopup.

If however, your target is inside of the bounds of the BubblePopup.Margin, then there might be a bug.  That being said, the only way I can know if that is true is if you can provide me a VisualStudio Solution that reproduces this issue.  I highly recommend this solution as a GitHub or BitBucket repo **AND** that you be sure to `.gitignore` the solution's `.bin` and `.obj` directories.
