### ISSUE TITLE
Build Error on iOS & Android Project

### ISSUE THREAD

**Issue by saamerm** [baskren/Forms9PatchDemo#7]
Error on Line 286 of PopupsPage.cs file while trying to Build the app on iOS.

Error shown as follows:
/Forms9PatchDemo-master/Source/Pages.Code/PopupsPage.cs(286,17,286,28): error CS0117: 'TargetedMenu' does not contain a definition for 'Orientation'

Error is fixed on iOS by commenting or removing out that line.

The problem exists on Android as well, and the code changes fixes the build on Android too

**Comment by baskren** [comment]
Demo apps have been moved to the `Demo` folder of the [Forms9Patch repository](https://github.com/baskren/Forms9Patch):

 - [Demo app using the Forms9Patch **NuGet package**](https://github.com/baskren/Forms9Patch/tree/master/Demo/UsingForms9PatchNuGet)
 - [Demo app using the Forms9Patch **source code**](https://github.com/baskren/Forms9Patch/tree/master/Demo/UsingForms9PatchSource)

This enables better visibility to issues with the demo apps as well as allow devs to optionally test with the Forms9Patch source code.
