### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by InquisitorJax** [baskren/Forms9PatchDemo#9]
Tried cloning the repo - multiple build errors.
After replacing HomePage with MainPage in App class:
![image](https://user-images.githubusercontent.com/1822976/60275991-07684d00-98fb-11e9-98bf-065973c172e4.png)

**Comment by baskren** [comment]
Demo apps have been moved to the `Demo` folder of the [Forms9Patch repository](https://github.com/baskren/Forms9Patch):

 - [Demo app using the Forms9Patch **NuGet package**](https://github.com/baskren/Forms9Patch/tree/master/Demo/UsingForms9PatchNuGet)
 - [Demo app using the Forms9Patch **source code**](https://github.com/baskren/Forms9Patch/tree/master/Demo/UsingForms9PatchSource)

This enables better visibility to issues with the demo apps as well as allow devs to optionally test with the Forms9Patch source code.
